/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthEditProfileRouteImport } from './routes/_auth/edit-profile'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthGroupsIndexRouteImport } from './routes/_auth/groups/index'
import { Route as AuthChatUsersUserIdRouteImport } from './routes/_auth/chat/users.$userId'
import { Route as AuthChatGroupsGroupIdRouteImport } from './routes/_auth/chat/groups.$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEditProfileRoute = AuthEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsIndexRoute = AuthGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatUsersUserIdRoute = AuthChatUsersUserIdRouteImport.update({
  id: '/chat/users/$userId',
  path: '/chat/users/$userId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatGroupsGroupIdRoute = AuthChatGroupsGroupIdRouteImport.update({
  id: '/chat/groups/$groupId',
  path: '/chat/groups/$groupId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/': typeof AuthIndexRoute
  '/groups': typeof AuthGroupsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/chat/groups/$groupId': typeof AuthChatGroupsGroupIdRoute
  '/chat/users/$userId': typeof AuthChatUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/': typeof AuthIndexRoute
  '/groups': typeof AuthGroupsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/chat/groups/$groupId': typeof AuthChatGroupsGroupIdRoute
  '/chat/users/$userId': typeof AuthChatUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/edit-profile': typeof AuthEditProfileRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/groups/': typeof AuthGroupsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/chat/groups/$groupId': typeof AuthChatGroupsGroupIdRoute
  '/_auth/chat/users/$userId': typeof AuthChatUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/edit-profile'
    | '/'
    | '/groups'
    | '/users'
    | '/chat/groups/$groupId'
    | '/chat/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/edit-profile'
    | '/'
    | '/groups'
    | '/users'
    | '/chat/groups/$groupId'
    | '/chat/users/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/edit-profile'
    | '/_auth/'
    | '/_auth/groups/'
    | '/_auth/users/'
    | '/_auth/chat/groups/$groupId'
    | '/_auth/chat/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/edit-profile': {
      id: '/_auth/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthEditProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/': {
      id: '/_auth/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthGroupsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/users/$userId': {
      id: '/_auth/chat/users/$userId'
      path: '/chat/users/$userId'
      fullPath: '/chat/users/$userId'
      preLoaderRoute: typeof AuthChatUsersUserIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/groups/$groupId': {
      id: '/_auth/chat/groups/$groupId'
      path: '/chat/groups/$groupId'
      fullPath: '/chat/groups/$groupId'
      preLoaderRoute: typeof AuthChatGroupsGroupIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthEditProfileRoute: typeof AuthEditProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthGroupsIndexRoute: typeof AuthGroupsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthChatGroupsGroupIdRoute: typeof AuthChatGroupsGroupIdRoute
  AuthChatUsersUserIdRoute: typeof AuthChatUsersUserIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEditProfileRoute: AuthEditProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthGroupsIndexRoute: AuthGroupsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthChatGroupsGroupIdRoute: AuthChatGroupsGroupIdRoute,
  AuthChatUsersUserIdRoute: AuthChatUsersUserIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
